name: Starttech-Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'starttech-infra/**'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Terraform Init
        working-directory: starttech-infra/terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: starttech-infra/terraform
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Validate
        working-directory: starttech-infra/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: starttech-infra/terraform
        run: terraform plan -no-color
        continue-on-error: true

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Terraform Init
        working-directory: starttech-infra/terraform
        run: terraform init

    
      - name: Terraform Apply
        working-directory: starttech-infra/terraform
        run: terraform apply --auto-approve

      - name: Terraform Output
        working-directory: starttech-infra/terraform
        run: terraform output -json > outputs.json

      - name: Display outputs
        working-directory: starttech-infra/terraform
        run: |
          echo "ğŸ“‹ Infrastructure Outputs:"
          terraform output
